AWSTemplateFormatVersion: '2010-09-09'
Description: >
  IAM Policies for CDK CloudFormation Execution Role
  This creates a custom managed policy with minimum required permissions
  for CDK to deploy Finance Project infrastructure.

  Usage:
    1. Deploy this stack first:
       AWS_PROFILE=finance aws cloudformation deploy \
         --template-file cfn-execution-policies.yaml \
         --stack-name FinanceCDKExecutionPolicies \
         --capabilities CAPABILITY_NAMED_IAM \
         --region ap-northeast-1

    2. Use the policy ARN for CDK bootstrap:
       AWS_PROFILE=finance cdk bootstrap \
         --cloudformation-execution-policies \
           arn:aws:iam::XXXXXXXXXXXX:policy/CDKCloudFormationExecutionPolicy-Finance \
         --region ap-northeast-1

Parameters:
  PolicyName:
    Type: String
    Default: CDKCloudFormationExecutionPolicy-Finance
    Description: Name of the IAM policy to create

Resources:
  # Custom Policy for CDK CloudFormation Execution Role
  CDKExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref PolicyName
      Description: Minimum required permissions for CDK to deploy Finance Project infrastructure
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # =====================================
          # Cognito Permissions
          # =====================================
          - Sid: CognitoUserPool
            Effect: Allow
            Action:
              - cognito-idp:CreateUserPool
              - cognito-idp:DeleteUserPool
              - cognito-idp:DescribeUserPool
              - cognito-idp:UpdateUserPool
              - cognito-idp:ListTagsForResource
              - cognito-idp:TagResource
              - cognito-idp:UntagResource
              - cognito-idp:SetUserPoolMfaConfig
              - cognito-idp:GetUserPoolMfaConfig
            Resource: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*'

          - Sid: CognitoUserPoolClient
            Effect: Allow
            Action:
              - cognito-idp:CreateUserPoolClient
              - cognito-idp:DeleteUserPoolClient
              - cognito-idp:DescribeUserPoolClient
              - cognito-idp:UpdateUserPoolClient
            Resource: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*'

          # =====================================
          # S3 Permissions
          # =====================================
          - Sid: S3Bucket
            Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:PutBucketPolicy
              - s3:DeleteBucketPolicy
              - s3:GetBucketPolicy
              - s3:PutBucketPublicAccessBlock
              - s3:GetBucketPublicAccessBlock
              - s3:PutBucketVersioning
              - s3:GetBucketVersioning
              - s3:PutBucketEncryption
              - s3:GetBucketEncryption
              - s3:PutBucketCORS
              - s3:GetBucketCORS
              - s3:PutBucketTagging
              - s3:GetBucketTagging
              - s3:PutBucketLogging
              - s3:GetBucketLogging
              - s3:PutLifecycleConfiguration
              - s3:GetLifecycleConfiguration
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource: 'arn:aws:s3:::*'

          - Sid: S3Object
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObjectVersion
              - s3:DeleteObjectVersion
            Resource: 'arn:aws:s3:::*/*'

          # =====================================
          # CloudFront Permissions
          # =====================================
          - Sid: CloudFrontDistribution
            Effect: Allow
            Action:
              - cloudfront:CreateDistribution
              - cloudfront:DeleteDistribution
              - cloudfront:GetDistribution
              - cloudfront:GetDistributionConfig
              - cloudfront:UpdateDistribution
              - cloudfront:TagResource
              - cloudfront:UntagResource
              - cloudfront:ListTagsForResource
              - cloudfront:CreateOriginAccessControl
              - cloudfront:DeleteOriginAccessControl
              - cloudfront:GetOriginAccessControl
              - cloudfront:GetOriginAccessControlConfig
              - cloudfront:UpdateOriginAccessControl
            Resource: '*'

          # =====================================
          # ACM Certificate (Read Only)
          # =====================================
          - Sid: ACMCertificate
            Effect: Allow
            Action:
              - acm:DescribeCertificate
              - acm:ListCertificates
              - acm:GetCertificate
              - acm:ListTagsForCertificate
            Resource: '*'

          # =====================================
          # SSM Parameter Store
          # =====================================
          - Sid: SSMParameter
            Effect: Allow
            Action:
              - ssm:PutParameter
              - ssm:DeleteParameter
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
              - ssm:DescribeParameters
              - ssm:AddTagsToResource
              - ssm:RemoveTagsFromResource
              - ssm:ListTagsForResource
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*'

          # =====================================
          # IAM Permissions (for CodeBuild roles, etc.)
          # =====================================
          - Sid: IAMRole
            Effect: Allow
            Action:
              - iam:CreateRole
              - iam:DeleteRole
              - iam:GetRole
              - iam:UpdateRole
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:GetRolePolicy
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:ListRolePolicies
              - iam:ListAttachedRolePolicies
              - iam:TagRole
              - iam:UntagRole
              - iam:UpdateAssumeRolePolicy
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/*'

          - Sid: IAMPolicy
            Effect: Allow
            Action:
              - iam:CreatePolicy
              - iam:DeletePolicy
              - iam:GetPolicy
              - iam:GetPolicyVersion
              - iam:ListPolicyVersions
              - iam:CreatePolicyVersion
              - iam:DeletePolicyVersion
              - iam:TagPolicy
              - iam:UntagPolicy
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/*'

          - Sid: IAMPassRole
            Effect: Allow
            Action:
              - iam:PassRole
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/*'
            Condition:
              StringEquals:
                iam:PassedToService:
                  - codebuild.amazonaws.com
                  - lambda.amazonaws.com
                  - apigateway.amazonaws.com
                  - cloudfront.amazonaws.com

          # =====================================
          # CodeBuild Permissions (for CI/CD stacks)
          # =====================================
          - Sid: CodeBuildProject
            Effect: Allow
            Action:
              - codebuild:CreateProject
              - codebuild:DeleteProject
              - codebuild:UpdateProject
              - codebuild:BatchGetProjects
              - codebuild:CreateWebhook
              - codebuild:DeleteWebhook
              - codebuild:UpdateWebhook
            Resource: !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/*'

          # =====================================
          # CodeConnections (for GitHub integration)
          # =====================================
          - Sid: CodeConnections
            Effect: Allow
            Action:
              - codeconnections:GetConnection
              - codeconnections:ListConnections
              - codestar-connections:GetConnection
              - codestar-connections:ListConnections
            Resource: '*'

          # =====================================
          # CloudWatch Logs (for Lambda, CodeBuild)
          # =====================================
          - Sid: CloudWatchLogs
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:DeleteLogGroup
              - logs:DescribeLogGroups
              - logs:PutRetentionPolicy
              - logs:DeleteRetentionPolicy
              - logs:TagLogGroup
              - logs:UntagLogGroup
              - logs:ListTagsForResource
            Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'

          # =====================================
          # Lambda Permissions (for Backend SAM deployment)
          # Note: This is for CDK to CREATE Lambda functions
          # The actual Lambda execution permissions are separate
          # =====================================
          - Sid: LambdaFunction
            Effect: Allow
            Action:
              - lambda:CreateFunction
              - lambda:DeleteFunction
              - lambda:GetFunction
              - lambda:UpdateFunctionCode
              - lambda:UpdateFunctionConfiguration
              - lambda:GetFunctionConfiguration
              - lambda:AddPermission
              - lambda:RemovePermission
              - lambda:TagResource
              - lambda:UntagResource
              - lambda:ListTags
              - lambda:PublishLayerVersion
              - lambda:DeleteLayerVersion
              - lambda:GetLayerVersion
              - lambda:InvokeFunction
            Resource:
              - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*'
              - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:*'

          # =====================================
          # API Gateway Permissions (for Backend SAM deployment)
          # =====================================
          - Sid: APIGateway
            Effect: Allow
            Action:
              - apigateway:GET
              - apigateway:POST
              - apigateway:PUT
              - apigateway:PATCH
              - apigateway:DELETE
            Resource: !Sub 'arn:aws:apigateway:${AWS::Region}:*:*'

          # =====================================
          # CloudFormation (for nested stacks, SAM Transform)
          # =====================================
          - Sid: CloudFormationStack
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:UpdateStack
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStackResources
              - cloudformation:GetTemplate
              - cloudformation:GetTemplateSummary
              - cloudformation:ListStackResources
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
            Resource: !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*'

          - Sid: CloudFormationSAMTransform
            Effect: Allow
            Action:
              - cloudformation:CreateChangeSet
            Resource: !Sub 'arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31'

          # =====================================
          # Application Insights & Resource Groups
          # (Used by SAM for monitoring)
          # =====================================
          - Sid: ApplicationInsights
            Effect: Allow
            Action:
              - applicationinsights:CreateApplication
              - applicationinsights:DeleteApplication
              - applicationinsights:DescribeApplication
            Resource: '*'

          - Sid: ResourceGroups
            Effect: Allow
            Action:
              - resource-groups:CreateGroup
              - resource-groups:DeleteGroup
              - resource-groups:GetGroup
              - resource-groups:GetTags
            Resource: '*'

Outputs:
  PolicyArn:
    Description: ARN of the created IAM policy for CDK CloudFormation Execution Role
    Value: !Ref CDKExecutionPolicy
    Export:
      Name: FinanceCDKExecutionPolicyArn

  PolicyName:
    Description: Name of the created IAM policy
    Value: !Ref PolicyName

  BootstrapCommand:
    Description: Command to use this policy with CDK bootstrap
    Value: !Sub |
      AWS_PROFILE=finance cdk bootstrap \
        --cloudformation-execution-policies ${CDKExecutionPolicy} \
        --region ${AWS::Region}
