version: 0.2

env:
  variables:
    # CDK deployment settings
    CDK_DEFAULT_REGION: "ap-northeast-1"
    CDK_EXECUTION_POLICY_NAME: "policy-finance-infra-cfn-execution"
  parameter-store:
    ACM_ARN: /Common/ACM/arn
    S3_CONTENTS_BUCKET_NAME: /Dashboard/S3/contents/bucket_name
    DYNAMODB_TABLE_NAME: /Dashboard/DynamoDB/main/table_name

phases:
  install:
    runtime-versions:
      python: 3.13
      nodejs: 20
    commands:
      - echo "Installing CDK CLI..."
      - npm install -g aws-cdk
      - echo "Creating Python virtual environment..."
      - python -m venv .venv
      - echo "Installing Python dependencies in virtual environment..."
      - .venv/bin/pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Creating config.json from config_sample.json..."
      - cp config_sample.json config.json
      - echo "Replacing ACM certificate ARN in config.json..."
      - sed -i "s|REPLACE_WITH_ACM_CERTIFICATE_ARN|${ACM_ARN}|g" config.json
      - echo "Replacing S3 contents bucket name in config.json..."
      - sed -i "s|REPLACE_WITH_S3_BUCKET_NAME|${S3_CONTENTS_BUCKET_NAME}|g" config.json
      - echo "Replacing DynamoDB table name in config.json..."
      - sed -i "s|REPLACE_WITH_DYNAMODB_TABLE_NAME|${DYNAMODB_TABLE_NAME}|g" config.json
      - echo "Checking CDK version..."
      - cdk --version
      - echo "Checking if CDK bootstrap is required..."
      - |
        if ! aws cloudformation describe-stacks --stack-name CDKToolkit --region ${CDK_DEFAULT_REGION} 2>/dev/null; then
          echo "CDKToolkit stack not found. Running CDK bootstrap..."
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          POLICY_ARN="arn:aws:iam::${ACCOUNT_ID}:policy/${CDK_EXECUTION_POLICY_NAME}"
          echo "Using CloudFormation execution policy: ${CDK_EXECUTION_POLICY_NAME}"
          echo "Policy ARN: ${POLICY_ARN}"
          cdk bootstrap --cloudformation-execution-policies ${POLICY_ARN} --region ${CDK_DEFAULT_REGION}
        else
          echo "CDKToolkit stack already exists. Skipping bootstrap."
        fi
      - echo "Listing CDK stacks..."
      - cdk list

  build:
    commands:
      - echo "Synthesizing CDK stacks..."
      - cdk synth
      - echo "Deploying all CDK stacks..."
      - cdk deploy --all --require-approval never

  post_build:
    commands:
      - echo "CDK deployment completed successfully!"
